<a href="https://colab.research.google.com/github/PreciousNalyanya/Numpy-Introduction/blob/main/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to numpy
<img >
> Add blockquote


standard library for Numerical Data in python(matrix and vectors)and forms the underlying foundation for libraries like Pandas and Matplotlib.

### Numpy Arrays
This is the main data structure in numpy
Single Fixed container with the followng properties:
   1. Single Data type
   2. Can be modified but size cannot change
   3. they can be one dimension or multi-dimension



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy as np

converting python list to a numpy array

In [ ]:
sales=[0,5,155,0,518,0,1827,616,317,325]
sales=np.array(sales)
sales

#print(type(sales))

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [ ]:
sales_as_numpy_array=np.array(sales)
sales_as_numpy_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

Numpy Array Properties

In [ ]:
# ndim: number of dimensions
# shape: size of array in each dimension
# size: the total number of elements
# dtype: the data type of the elements
print(f"Ndim:{sales_as_numpy_array.ndim}")
print(f"Shape:{sales_as_numpy_array.shape}")
print(f"Size:{sales_as_numpy_array.size}")
print(f"Dtype:{sales_as_numpy_array.dtype}")
# you can use it without f" "
# print(sales_as_numpy_array.ndim)

Ndim:1
Shape:(10,)
Size:10
Dtype:int64


In [ ]:
sales2=[[0,5,155,0,518],[0,18,27,616,317]]
sales2_as_numpy_array=np.array(sales2)
sales2_as_numpy_array

array([[  0,   5, 155,   0, 518],
       [  0,  18,  27, 616, 317]])

In [ ]:
print(f"Ndim:{sales2_as_numpy_array.ndim}")
print(f"Shape:{sales2_as_numpy_array.shape}")
print(f"Size:{sales2_as_numpy_array.size}")
print(f"Dtype:{sales2_as_numpy_array.dtype}")

Ndim:2
Shape:(2, 5)
Size:10
Dtype:int64


Array Operations

In [ ]:
sales2_as_numpy_array

array([[  0,   5, 155,   0, 518],
       [  0,  18,  27, 616, 317]])

In [ ]:
#1. Adding a scalar(single value)
sales2_as_numpy_array+2

array([[  2,   7, 157,   2, 520],
       [  2,  20,  29, 618, 319]])

In [ ]:
# 2.Accessing a Multi-Dimension Array
# [rows, columns]
sales2_as_numpy_array[0:2,0:5]

array([[  0,   5, 155,   0, 518],
       [  0,  18,  27, 616, 317]])

In [ ]:
# All the records, first three columns
sales2_as_numpy_array[:,0:3]

array([[  0,   5, 155],
       [  0,  18,  27]])

In [ ]:
#3. filtering Arrays
# access where sales is not equal to zero
sales2_as_numpy_array !=0
# syntax:array[condition]
sales2_as_numpy_array[sales2_as_numpy_array!=0]

array([  5, 155, 518,  18,  27, 616, 317])

In [ ]:
# Sales equal to 616 or sales less than 100
(sales2_as_numpy_array==616) | (sales2_as_numpy_array<100)
# syntax:array[condition]
sales2_as_numpy_array[(sales2_as_numpy_array==616) | (sales2_as_numpy_array<100)]


array([  0,   5,   0,   0,  18,  27, 616])

In [29]:
# sales more than 100 and sales less than 500
(sales2_as_numpy_array>100) & (sales2_as_numpy_array<500)
sales2_as_numpy_array[(sales2_as_numpy_array>100) & (sales2_as_numpy_array<500)]
# or
condition=(sales2_as_numpy_array>100) & (sales2_as_numpy_array<500)
sales2_as_numpy_array[condition]

array([155, 317])

In [ ]:
# List Comprehension
list_5=[1,2,3,4,5]
print(type(list_5))

<class 'list'>


In [ ]:
list_10=[x for x in range(10)]
print(list_10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
list_10_even=[x*2 for x in range(11)]
print(list_10_even)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [ ]:
# Using List Comprehension Create List of the 50 multiple of 5 e.g 0, 5,10
list_of_the_50_multiple=[x*5 for x in range(11)]
print(list_of_the_50_multiple)

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


In [ ]:
# Array Creation
# np.zeros()
# np.ones()
# np.arange
# np.linspace
# np.array.reshape
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [ ]:
np.arange(2,13,2).reshape(2,3)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
from numpy.random import default_rng
rand=default_rng(123)
rand.random((10))

array([0.68235186, 0.05382102, 0.22035987, 0.18437181, 0.1759059 ,
       0.81209451, 0.923345  , 0.2765744 , 0.81975456, 0.88989269])

In [ ]:
from numpy.random import default_rng
rand=default_rng(123)
numbers=rand.random((3,2))
numbers

array([[0.68235186, 0.05382102],
       [0.22035987, 0.18437181],
       [0.1759059 , 0.81209451]])

In [ ]:
score=default_rng(123)
score=score.normal(loc=80,scale=10,size=5)
score

array([70.1087865 , 76.32213349, 92.87925261, 81.93974419, 89.202309  ])

In [24]:
# Indexing/slicing numpy arrays
counties=["nairobi","kisumu","kericho","nakuru","kilifi","kiambu","laikipia","nyeri"]
counties_array=np.array(counties).reshape(2,4)
counties_array

array([['nairobi', 'kisumu', 'kericho', 'nakuru'],
       ['kilifi', 'kiambu', 'laikipia', 'nyeri']], dtype='<U8')

In [26]:
kilifi_county=counties_array[1,0]
kilifi_county

'kilifi'

In [28]:
# access for all the records the first two colums
counties_array.shape
counties_array[:,:2]

array([['nairobi', 'kisumu'],
       ['kilifi', 'kiambu']], dtype='<U8')

In [30]:
#filtering using Where condition(ifblock,elseblock) condition
sales_inventory=np.array([12,18,102,0,0])
sales_inventory

array([ 12,  18, 102,   0,   0])

In [31]:
# where
np.where(sales_inventory<0,"Out of Stock","In Stock")

array(['In Stock', 'In Stock', 'In Stock', 'In Stock', 'In Stock'],
      dtype='<U12')

In [32]:
# products array
products_array=np.array(["egg","milk","bread","beans","rice"])
products_array

array(['egg', 'milk', 'bread', 'beans', 'rice'], dtype='<U5')

In [33]:
np.where(sales_inventory<=0,"Out of Stock",products_array)

array(['egg', 'milk', 'bread', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [34]:
# Array aggregation methods
# 1.sum() mean() count() median() std()var()max()min()
sales_as_numpy_array.sum()

3763

In [36]:
sales_as_numpy_array.min()

0

In [37]:
sales_as_numpy_array.max()

1827

In [39]:
np.percentile(sales_as_numpy_array,[25,75])

array([  1.25, 469.75])